import React from "react"
import "./App.css"
export default function App() {


    return <main>
       <h1 className="h1 text-center">
        App Template h1
        </h1> 
       <h2 className="h2">
        h2
        </h2> 
       <h3 className="h3">
        h3
        </h3> 
       <h4 className="h4">
        h4
        </h4> 
        <p className="my-4 p">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</p>
        <blockquote className="my-4 lockquote">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</blockquote>
        <span className="my-4 inline-code">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</span>
        <p className="my-4 lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</p>
        <p className="my-4 large">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</p>
        <p className="my-4 small">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</p>
        <p className="my-4 muted">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dolor consequuntur omnis ab nesciunt iste fugit incidunt minus at quibusdam cupiditate laudantium sapiente expedita libero sunt nisi consequatur deserunt, dignissimos, tempora magnam corporis. Perspiciatis veritatis, beatae consequatur accusantium voluptatem, odio numquam quibusdam iure tenetur sapiente harum magni doloribus delectus in veniam id ea facere mollitia vitae voluptatibus vel suscipit. Et natus quibusdam error ad magni voluptates voluptatem minima cumque! Magnam dicta quam molestias nesciunt mollitia ad nisi. Reprehenderit praesentium cupiditate in nisi, illum voluptas tempore exercitationem facilis accusantium ab voluptatum eius ullam beatae libero repellat minus iste, inventore recusandae ad.</p>
        
        </main>

}